apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2023-11-26T11:06:55Z"
  generation: 502
  name: jekajenkins
  namespace: argocd
  resourceVersion: "1651098"
  uid: 79ace637-398e-46ee-86b1-6dad05c69f49
spec:
  destination:
    namespace: jenkinshw14
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: Jenkins
    repoURL: https://ymazurau.github.io/14.Homework.Jenkins_helm/
    targetRevision: 0.1.0
  syncPolicy:
    automated: {}
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2023-11-26T11:07:00Z"
    deployedAt: "2023-11-26T11:07:03Z"
    id: 0
    revision: 0.1.0
    source:
      chart: Jenkins
      repoURL: https://ymazurau.github.io/14.Homework.Jenkins_helm/
      targetRevision: 0.1.0
  operationState:
    finishedAt: "2023-11-26T11:07:03Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: 0.1.0
    phase: Succeeded
    startedAt: "2023-11-26T11:07:00Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/jenkinshw14 created
        name: jenkinshw14
        namespace: jenkinshw14
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/my-basic-config created
        name: my-basic-config
        namespace: jenkinshw14
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/my-jenkins-config created
        name: my-jenkins-config
        namespace: jenkinshw14
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: "clusterrolebinding.rbac.authorization.k8s.io/jekajenkins-binding
          reconciled. reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount
          APIGroup: Name:default Namespace:jenkinshw14}. clusterrolebinding.rbac.authorization.k8s.io/jekajenkins-binding
          configured. Warning: resource clusterrolebindings/jekajenkins-binding is
          missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically."
        name: jekajenkins-binding
        namespace: jenkinshw14
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/jekajenkins created
        name: jekajenkins
        namespace: jenkinshw14
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/jekajenkins created
        name: jekajenkins
        namespace: jenkinshw14
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/helm-j-jenkins-ingress created
        name: helm-j-jenkins-ingress
        namespace: jenkinshw14
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 0.1.0
      source:
        chart: Jenkins
        repoURL: https://ymazurau.github.io/14.Homework.Jenkins_helm/
        targetRevision: 0.1.0
  reconciledAt: "2023-11-27T11:27:51Z"
  resources:
  - kind: ConfigMap
    name: my-basic-config
    namespace: jenkinshw14
    status: Synced
    version: v1
  - kind: ConfigMap
    name: my-jenkins-config
    namespace: jenkinshw14
    status: Synced
    version: v1
  - kind: Namespace
    name: jenkinshw14
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: jekajenkins
    namespace: jenkinshw14
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: jekajenkins
    namespace: jenkinshw14
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: helm-j-jenkins-ingress
    namespace: jenkinshw14
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: jekajenkins-binding
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    externalURLs:
    - http://jenkinshw14.k8s-8.sa/
    images:
    - jfrog.it-academy.by/public/jenkins-ci:spishchyk_01
  sync:
    comparedTo:
      destination:
        namespace: jenkinshw14
        server: https://kubernetes.default.svc
      source:
        chart: Jenkins
        repoURL: https://ymazurau.github.io/14.Homework.Jenkins_helm/
        targetRevision: 0.1.0
    revision: 0.1.0
    status: Synced