apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2023-11-26T12:45:19Z"
  generation: 489
  name: jenkins
  namespace: argocd
  resourceVersion: "1651097"
  uid: 894ee818-88cc-47d5-a03d-a5d81d37d14b
spec:
  destination:
    namespace: ci-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./
    repoURL: https://github.com/YMazurau/14.K8s.Deployment-DEMO.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2023-11-26T12:45:20Z"
    deployedAt: "2023-11-26T12:45:41Z"
    id: 0
    revision: 220ae68d689163d4d1ecb53d95e89d5af8a877ab
    source:
      path: ./
      repoURL: https://github.com/YMazurau/14.K8s.Deployment-DEMO.git
      targetRevision: master
  - deployStartedAt: "2023-11-26T12:50:56Z"
    deployedAt: "2023-11-26T12:50:58Z"
    id: 1
    revision: 220ae68d689163d4d1ecb53d95e89d5af8a877ab
    source:
      path: ./
      repoURL: https://github.com/YMazurau/14.K8s.Deployment-DEMO.git
      targetRevision: master
  operationState:
    finishedAt: "2023-11-26T12:50:58Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 220ae68d689163d4d1ecb53d95e89d5af8a877ab
        syncOptions:
        - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2023-11-26T12:50:56Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/ci-cd created
        name: ci-cd
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Secret
        message: secret/jenkins-secret created
        name: jenkins-secret
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/basic-security created
        name: basic-security
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/jenkins-config created
        name: jenkins-config
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: "clusterrolebinding.rbac.authorization.k8s.io/jenkins reconciled.
          reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount
          APIGroup: Name:default Namespace:ci-cd}. clusterrolebinding.rbac.authorization.k8s.io/jenkins
          configured. Warning: resource clusterrolebindings/jenkins is missing the
          kubectl.kubernetes.io/last-applied-configuration annotation which is required
          by  apply.  apply should only be used on resources created declaratively
          by either  create --save-config or  apply. The missing annotation will be
          patched automatically."
        name: jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/jenkins created
        name: jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/jenkins created
        name: jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/ingress-jenkins created
        name: ingress-jenkins
        namespace: ci-cd
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 220ae68d689163d4d1ecb53d95e89d5af8a877ab
      source:
        path: ./
        repoURL: https://github.com/YMazurau/14.K8s.Deployment-DEMO.git
        targetRevision: master
  reconciledAt: "2023-11-27T11:27:51Z"
  resources:
  - kind: ConfigMap
    name: basic-security
    namespace: ci-cd
    status: Synced
    version: v1
  - kind: ConfigMap
    name: jenkins-config
    namespace: ci-cd
    status: Synced
    version: v1
  - kind: Namespace
    name: ci-cd
    status: Synced
    version: v1
  - kind: Secret
    name: jenkins-secret
    namespace: ci-cd
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: ingress-jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: jenkins
    status: Synced
    version: v1
  sourceType: Directory
  summary:
    externalURLs:
    - http://jenkins.k8s-8.sa/
    images:
    - jfrog.it-academy.by/public/jenkins-ci:spishchyk_01
  sync:
    comparedTo:
      destination:
        namespace: ci-cd
        server: https://kubernetes.default.svc
      source:
        path: ./
        repoURL: https://github.com/YMazurau/14.K8s.Deployment-DEMO.git
        targetRevision: master
    revision: 220ae68d689163d4d1ecb53d95e89d5af8a877ab
    status: Synced