apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2023-11-26T16:06:15Z"
  generation: 416
  name: nfs-subdir-external-provisioner
  namespace: argocd
  resourceVersion: "1651353"
  uid: 48f69e02-3772-4090-b6a5-b824583c6249
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    helm:
      parameters:
      - name: nfs.path
        value: ' /mnt/IT-Academy/nfs-data/sa2-25-23/'
      - name: storageClass.name
        value: nfs
      - name: nfs.server
        value: 192.168.37.105
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.18
  syncPolicy:
    automated: {}
status:
  conditions:
  - lastTransitionTime: "2023-11-26T16:11:33Z"
    message: 'Failed sync attempt to 4.0.18: one or more objects failed to apply,
      reason: StorageClass.storage.k8s.io "nfs" is invalid: provisioner: Forbidden:
      updates to provisioner are forbidden. (retried 5 times).'
    type: SyncError
  controllerNamespace: argocd
  health:
    status: Healthy
  operationState:
    finishedAt: "2023-11-26T16:11:32Z"
    message: 'one or more objects failed to apply, reason: StorageClass.storage.k8s.io
      "nfs" is invalid: provisioner: Forbidden: updates to provisioner are forbidden.
      (retried 5 times).'
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: 4.0.18
    phase: Failed
    retryCount: 5
    startedAt: "2023-11-26T16:06:16Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: ServiceAccount
        message: serviceaccount/nfs-subdir-external-provisioner unchanged
        name: nfs-subdir-external-provisioner
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: storage.k8s.io
        hookPhase: Failed
        kind: StorageClass
        message: 'StorageClass.storage.k8s.io "nfs" is invalid: provisioner: Forbidden:
          updates to provisioner are forbidden.'
        name: nfs
        namespace: default
        status: SyncFailed
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRole
        message: clusterrole.rbac.authorization.k8s.io/nfs-subdir-external-provisioner-runner
          reconciled. clusterrole.rbac.authorization.k8s.io/nfs-subdir-external-provisioner-runner
          unchanged
        name: nfs-subdir-external-provisioner-runner
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: clusterrolebinding.rbac.authorization.k8s.io/run-nfs-subdir-external-provisioner
          reconciled. clusterrolebinding.rbac.authorization.k8s.io/run-nfs-subdir-external-provisioner
          unchanged
        name: run-nfs-subdir-external-provisioner
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: Role
        message: role.rbac.authorization.k8s.io/leader-locking-nfs-subdir-external-provisioner
          reconciled. role.rbac.authorization.k8s.io/leader-locking-nfs-subdir-external-provisioner
          unchanged
        name: leader-locking-nfs-subdir-external-provisioner
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: RoleBinding
        message: rolebinding.rbac.authorization.k8s.io/leader-locking-nfs-subdir-external-provisioner
          reconciled. rolebinding.rbac.authorization.k8s.io/leader-locking-nfs-subdir-external-provisioner
          unchanged
        name: leader-locking-nfs-subdir-external-provisioner
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/nfs-subdir-external-provisioner configured
        name: nfs-subdir-external-provisioner
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 4.0.18
      source:
        chart: nfs-subdir-external-provisioner
        helm:
          parameters:
          - name: nfs.path
            value: ' /mnt/IT-Academy/nfs-data/sa2-25-23/'
          - name: storageClass.name
            value: nfs
          - name: nfs.server
            value: 192.168.37.105
        repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
        targetRevision: 4.0.18
  reconciledAt: "2023-11-27T11:30:51Z"
  resources:
  - kind: ServiceAccount
    name: nfs-subdir-external-provisioner
    namespace: default
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: nfs-subdir-external-provisioner
    namespace: default
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: nfs-subdir-external-provisioner-runner
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: run-nfs-subdir-external-provisioner
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: leader-locking-nfs-subdir-external-provisioner
    namespace: default
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: leader-locking-nfs-subdir-external-provisioner
    namespace: default
    status: Synced
    version: v1
  - group: storage.k8s.io
    kind: StorageClass
    name: nfs
    status: OutOfSync
    version: v1
  sourceType: Helm
  summary:
    images:
    - registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        chart: nfs-subdir-external-provisioner
        helm:
          parameters:
          - name: nfs.path
            value: ' /mnt/IT-Academy/nfs-data/sa2-25-23/'
          - name: storageClass.name
            value: nfs
          - name: nfs.server
            value: 192.168.37.105
        repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
        targetRevision: 4.0.18
    revision: 4.0.18
    status: OutOfSync